### ISSUE TITLE
Can't install on Ubuntu

### ISSUE THREAD

**Issue by LarisaKozhekina** [ANTsX/ANTsPy#115]
I tried to install antspy by command:
_pip3 install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl_
So it was written - Successfully installed antspy-0.1.4

I did it for Linux and for Anaconda. But in both cases after _'import ants'_ import start but then i got:
_No module named 'antsImage'_

I am a beginner in Linux. What did i do wrong?

**Comment by halirutan** [comment]
Version 0.1.4 is pretty old (we're currently at 0.2.2). The most direct way is to compile the latest version yourself, but that might not be trivial for a beginner since you very likely will have to install additional dependencies.

If you tell what exact system you have and if you're using Python 3.7, then I can provide you with a newer `whl` file for your system. What is the output if you type `uname -a` in a terminal?

**Comment by halirutan** [comment]
Additionally, have you tried installing one of the `whl` [files from here]( https://github.com/ANTsX/ANTsPy/releases/tag/v0.2.0)?

**Comment by stnava** [comment]
a variety of linux wheels will become available via `pip install` here: https://pypi.org/project/antspyx/ 

I haven't tested these but tried to follow what is supposed to be current best practices in hopes that more users will be able to install from wheels.

**Comment by stnava** [comment]
please reopen if issues persists.
