### ISSUE TITLE
Coregister for label doesn't work correctly

### ISSUE THREAD

**Issue by LarisaKozhekina** [ANTsX/ANTsPy#141]
**Describe the bug**
In my dataset i have three mri mode image (T1,T1c,Flair). I need to coregister them for neural network input together. Now i try to coregister flair image and label for it with mni template. But after coregister my label doesn't match my image. It is shifted wrong or dissappear.
I use the same transformation for image and label. And use mni as template for both.
[coregister.txt](https://github.com/ANTsX/ANTsPy/files/4422872/coregister.txt)

**To Reproduce**
1. Run script from coregister.txt

**Expected behavior**
Image and label before coregister:
![before_correg_img](https://user-images.githubusercontent.com/16781515/78284229-c35c4580-7527-11ea-9fd5-a53405da038a.PNG)

Image and label after coregister:
![after_correg_img_1](https://user-images.githubusercontent.com/16781515/78284270-d3742500-7527-11ea-9220-7a4b8ada023e.PNG)
![after_correg_img_2](https://user-images.githubusercontent.com/16781515/78284275-d5d67f00-7527-11ea-8977-21c17233776a.PNG)

As we see, label was shifted by all axis.

**Desktop (please complete the following information):**

- numpy version 1.18.2.
- Google Colaboratory.
- Python 3.6.9:
- Ants from pip install antspyx '0.2.5'

**Comment by stnava** [comment]
this application goal is very simple/traditional and quite well-vetted.

please compare your code to existing examples in order to find out where your mistake may lie.   

e.g.

https://github.com/ANTsX/ANTsPy/blob/master/tutorials/concatenateRegistrations.ipynb

often when users raise this type of issue, it is because your data does not conform to ants standards, you are mixing software packages or just making a simple mistake in applying transforms.

**Comment by stnava** [comment]
please reopen if you need more help with this issue.
