### ISSUE TITLE
WARNING: GaussianOperator: Kernel size has exceeded the specified the specified maximum width of 6

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#262]
While doing image registration, I am getting the following warning:

> WARNING: In /home/user/ANTsPy/itksource/Modules/Core/Common/include/itkGaussianOperator.hxx, line 56
> GaussianOperator (0x7ffcf39b76d0): Kernel size has exceeded the specified maximum width of 6 and has been truncated to 7 elements.  You can raise the maximum width using the SetMaximumKernelWidth method.

I am assuming this relates to the size of the Gaussian kernel being used during registration. Does this truncation have an effect on the quality of registration? Would increasing the limit of this kernel have an effect on accuracy or the speed of the registration overall? Or is it recommended to leave this setting to its default?

Also, I could not find the SetMaximumKernelWidth method in the documentation. How is this method used?

I am specifically using the SynRA method for registration.

**Comment by ntustison** [comment]
``SetMaximumKernelWidth`` is buried in the internals of the registration code---certainly not something which we would provide access to by the user.  When this issue surfaces, it's usually due to a degenerate registration scenario such as 3-D registrations where one or both of the 3-D image volumes comprise less than a handful of slices.
