### ISSUE TITLE
Transform 3D model

### ISSUE THREAD

**Issue by alexeytopolnitskiy** [ANTsX/ANTsPy#278]
Hi! 

I have a 3D model in numpy.ndarray and 3 angles of transformation for each direction (x,y,z). Can I transform my 3D model using these 3 angles using ANTs?

**Comment by stnava** [comment]
yes - but you would have to figure out the details of how to do so which would require in-depth understanding of medical imaging physical space definitions and how these map to the spaces you defined.  if you are clever with geometry, relatively quickly ( an hour or so ), otherwise could take considerably longer.

**Comment by stnava** [comment]
reopen if you have further feedback  /  questions
