### ISSUE TITLE
ANTsPy for windows

### ISSUE THREAD

**Issue by sulaimanvesal** [ANTsX/ANTsPy#301]
I wanted to know if there is any progress on ANTsPy windows version! or any instruction on how to compile it on Windows?

**Comment by stnava** [comment]
I have not heard of any progress wrt native windows.   the windows linux subsystem gets around this limitations.

**Comment by haesleinhuepf** [comment]
Hi, 

are there any news on this?

I would love to use this in project, unfortunately most of my collaborators work with windows.

Thanks,
Robert

**Comment by sanshitangmalaban** [comment]
sad

**Comment by kchawla-pi** [comment]
What are the sticking points/blockers in building windows wheels? I may want to look into trying to build them. Anything I need to know?

**Comment by cookpa** [comment]
> I wanted to know if there is any progress on ANTsPy windows version! or any instruction on how to compile it on Windows?

Working Windows wheels are available now via #442. Because of space limitations they may not be on PyPI, but recent builds are available via Github actions (good for 30 days, see https://github.com/ANTsX/ANTsPy/actions/runs/4490025018), and I hope to have wheels for all platforms pinned to releases going forward.

**Comment by ntustison** [comment]
Awesome.  Thanks again @cookpa

**Comment by sulaimanvesal** [comment]
This is great @cookpa, thanks for the update.
