### ISSUE TITLE
Consider adopting PEP-8 

### ISSUE THREAD

**Issue by rueberger** [ANTsX/ANTsPy#328]
Readability could be improved by conforming to PEP-8. Very easy to do with a formatter such as [black](https://github.com/psf/black) before commiting and also as a build step in github's CI tool.

**Comment by ncullen93** [comment]
Apologies for getting to this extremely late.. but this is something I am going to implement and just wanted to ask if you had an opinion on which step in the process you think it's best to implement something like autopep8. Upon each PR, only on push to main branch, or as a cron job once per day? Or something else? 

Closing the issue due to inactivity but feel free to respond if you see this :) Thanks!

**Comment by rueberger** [comment]
probably easiest just to do it all at once and then enforce for future PRs
