### ISSUE TITLE
build_template should return transforms

### ISSUE THREAD

**Issue by Hierakonpolis** [ANTsX/ANTsPy#352]
**Is your feature request related to a problem? Please describe.**
In analogy with the buildtemplateparallel script, it would make sense to actually return the transforms for the template built in antspy, as to be useful the template will need the backwards and forward transforms anyway.

**Describe the solution you'd like**
It could be returned as a structured object or even as a set of loose files in a folder, but somehow it should return the transforms utilized. I hope I haven't missed this feature somewhere but it doesn't seem to be there.

**Describe alternatives you've considered**
One could run the registration again, but that's far from the optimal solution.

**Comment by ntustison** [comment]
At the end of the template construction process, the transforms do not correspond precisely with the template.  Rather, the transforms correspond to the template produced at the end of the previous iteration.  That's why we recommend to run pairwise registration again, as mentioned in the "aternatives you've considered."

**Comment by stnava** [comment]
the procedure does this:

* register the images to the current template - transformations are  in `template_k` space
* update the template shape and appearance - this creates  `template_k+1`

so registrations will be accurate for the previous but not current template.
