### ISSUE TITLE
Troubles in converting ANTsImage to PIL image.

### ISSUE THREAD

**Issue by gentlezr** [ANTsX/ANTsPy#379]
**Describe the bug**
Hi,  I have troubles in converting ANTsImage to PIL image. Please run this scripts and you can find that 'fixA2.png' is different to 'A.png' or 'fixA1.png'. It shows that ants.to_file() have some tricks I don't know.

`from PIL import Image
import numpy as np
import ants

path = 'A.png'
to_dir = '.'
img = ants.from_numpy(np.array(Image.open(path)))

Image.fromarray(np.array(img.numpy())).save(os.path.join(to_dir, 'fixA1.png'))
img.to_file(os.path.join(to_dir, 'fixA2.png'))`

**A.png**
![A](https://user-images.githubusercontent.com/29143300/174032598-6bc051fb-8868-4718-ab22-b35501a0d475.png)

**fixA1.png**
![image](https://user-images.githubusercontent.com/29143300/174032720-b45ad98a-2eec-4d72-aa52-cdcee1b00d21.png)

**fixA2.png**
![image](https://user-images.githubusercontent.com/29143300/174032759-7022dbf1-272e-473c-8a30-598661d89b22.png)

**Comment by cookpa** [comment]
This happens because ANTsPy expects image indices in row,column (x,y) order, while PIL uses column,row (y,x). So you either need to transpose the numpy matrix, or set the header of the ANTs image - by default it assumes an identity transform between the pixel indices and physical space.

Beware also that the PNG image above has three color channels; I could not read it as RGB but I could do

img = ants.from_numpy(np.array(Image.open(path)), has_components=True)
