### ISSUE TITLE
Fatal Python error: Segmentation fault during registration

### ISSUE THREAD

**Issue by vascosa** [ANTsX/ANTsPy#40]
Hello,

I am getting a Segfault error while trying to register an 4D volume to a 3D volume. 
```
tx_func2t1 = ants.registration(fixed=fixed, moving=moving, type_of_transform='Rigid')
```

I get this error but I'm not sure what is going on here:

> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fea0e272740 (most recent call first):
>   File "/home/vasco/.local/lib/python3.6/site-packages/ants/registration/interface.py", line 651 in registration
>   File "resting_pipeline_ants.py", line 711 in step4
>   File "resting_pipeline_ants.py", line 126 in __init__
>   File "resting_pipeline_ants.py", line 1385 in <module>

 Any clues? Thanks in advance.

**Comment by stnava** [comment]
it works for ND to ND registration only.

e.g.  256x256x1 to 256x256x256 is ok.

but 256x256 to  256x256x256 is not.

brian

**Comment by Vathsan** [comment]
Hi @stnava,

I am getting the same error while trying to register a 2D tif image. Following is a sample image header information,
`ants size:  {'pixelclass': 'rgb', 'pixeltype': 'unsigned char', 'nDimensions': 2, 'nComponents': 3, 'dimensions': (2400.0, 864.0), 'spacing': (1.0, 1.0), 'origin': (0.0, 0.0), 'direction': array([[1., 0.], [0., 1.]])} `

ANTsImage is read from file,
`fixed = ants.image_read(fixed_tif, dimension = 3)`

I could see the following details by printing the ANTsImage,
```
ANTsImage (RAI)
	 Pixel Type : float (float32)
	 Components : 3 (RGB)
	 Dimensions : (1200, 864, 1)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (0.0, 0.0, 0.0)
	 Direction  : [1. 0. 0. 0. 1. 0. 0. 0. 1.]
```
Should not this work since the image dimension is 1200x864x1? Appreciate any help on this. Thanks in advance.

**Comment by ntustison** [comment]
Please don't post under a closed issue.  Rather, open a new issue to ask about your problem.

**Comment by Vathsan** [comment]
> Please don't post under a closed issue. Rather, open a new issue to ask about your problem.

Reported issue https://github.com/ANTsX/ANTsPy/issues/354.
