### ISSUE TITLE
Results are flipped when using ants.apply_transforms()

### ISSUE THREAD

**Issue by DimitriosGk** [ANTsX/ANTsPy#422]
Hello,

I am using the ants.apply_transforms() to apply a transformation to some additional images after registration of 2 MRI volumes. Specifically in the code:
------------------------------------------------------------------------------------------------------------------------
    """
    Registration-------------------------------------------------------------------
    """
    print('STEP: Registration (Initial affine)..................')    
    tx_filename = os.path.join(output_dir,'init_affine_Transform.mat')
    ## Make initial Affine transform, to bring images on the same space------------
    txfile = ants.affine_initializer(GRE_Magn_biasCorr_denoised, 
                                     MP2RAGE_INV2, 
                                     search_factor=20, 
                                     radian_fraction=0.6, 
                                     use_principal_axis=False, 
                                     local_search_iterations=20, 
                                     mask=None, 
                                     txfn=tx_filename)
    tx = ants.read_transform(txfile, dimension=2)
    
    ## Apply transform to moving image---------------------------------------------
    init_trasf_INV2 = tx.apply_to_image(MP2RAGE_INV2, 
                                  reference=GRE_Magn_biasCorr_denoised, 
                                      interpolation='linear')
    
    ## Check Result visually-------------------------------------------------------
    print('Post-initial affine comparison----------------------------------------')
    ants.plot( GRE_Magn_biasCorr_denoised, init_trasf_INV2, overlay_alpha = 0.4 )
    
    print('STEP: Registration (Non-linear)..................')    
    ## Non-linear registration of images-------------------------------------------
    reg = ants.registration(fixed=GRE_Magn_biasCorr_denoised, 
                            moving=init_trasf_INV2, 
                            type_of_transform = 'SyN',
                            reg_iterations = [100,100,50] )
    
    MP2RAGE_INV2_reg = reg['warpedmovout']
    ## Check Result visually-------------------------------------------------------
    print('Final registration comparison-----------------------------------------')
    ants.plot( GRE_Magn_biasCorr_denoised, MP2RAGE_INV2_reg, overlay_alpha = 0.4, nslices = 20 )
    
    
    print('STEP: Applying transforms to the  wanted volumes..................')    
    ## Apply transform to other images (masks from segmentation)-------------------
    fullTrasform = reg[ 'invtransforms'] 
    fullTrasform.append(txfile)
    
    MP2RAGE_UNI_biasCorr_denoised_reg = ants.apply_transforms( fixed = GRE_Magn_biasCorr_denoised,
                                                              moving = MP2RAGE_UNI_biasCorr_denoised, transformlist = fullTrasform, 
                                                              interpolator  = 'linear', whichtoinvert = [False,False,False])

------------------------------------------------------------------------------------------------------------------------

The direct results of the registration (reg['warpedmovout']), both in ants.plot() and in the saved .nii files appear to be fine. The problem occurs on the volumes that I try to apply the transforms to. The final result appears to be flipped both in ants.plot() and in the saved .nii files (please see images attached, image 1 shows the registration result, Image 2 the problematic one).  

![1](https://user-images.githubusercontent.com/29710018/212338938-4531f1e7-11f7-4954-9e07-d8699fac6119.png)
Image 1

![2](https://user-images.githubusercontent.com/29710018/212339013-6f567ef8-77e2-4ff1-9571-04bf060e655c.png)
Image 2

In advance I need to say that the image used for registration and the ones I apply the transform to post-registration are coming from the same processing source and have no differences in headers that I can see (can be found here: https://drive.google.com/drive/folders/1q0zwpbnQjWR7l77UMq3rXsyxOdWGMTw_?usp=sharing).
Any idea why this occurs?

Thanks a lot!
Dimitri

ps. in the google drive files, the ref is Magn_echo_1_masked.nii.gz, the moving image is GTSPc004_MP2RAGE_INV2_masked.nii.gz and the rest are in the same space as the moving image and resulting transform is applied on them.

**Comment by ntustison** [comment]
I downloaded the directory "flipping_issues" and tried to run ``preProcessing_3T_Registration_PET2QSM.py`` after 
changing ``your_dir`` to the appropriate location.

However, I'm getting a "file does not exist" error.  After a quick look, I see on line 17, you have a subdirectory ``QSM`` which is not in the downloaded directory:

``
GRE_Magn_QSM_dir = os.path.join(input_dir,'QSM/Magn_echo_1_masked.nii.gz')
``

Please check again and make the appropriate changes so I can just run it without having to go through the code to make the necessary changes.

**Comment by DimitriosGk** [comment]
Hello,

That's right, I forgot to remove the directory. I changed it and tested it now again, it shall run without interruption.

Dimitri

**Comment by cookpa** [comment]
Yes, if qform_code and sform_code are both 0, ITK falls back on Analyze 7.5 logic and attempts to guess the orientation. However, ITK will always write images with qform and sform set to the same rigid transform.

The reference image header should be fixed so that the image has a valid sform (preferred) or qform, and the anatomical labels look correct when the image is loaded with ITK-SNAP.

**Comment by DimitriosGk** [comment]
Hi, thanks for the effort.
I understand the part of the qform/sform  and I suppose it is easily fixable in the reference image. I still try to understand the involvement of the actual anatomical orientation of the image though. 
How does it affect the result? The registration seems correct, even with the reference image being non-anatomically correct labeled.

**Comment by ntustison** [comment]
> I still try to understand the involvement of the actual anatomical orientation of the image though.
How does it affect the result? The registration seems correct, even with the reference image being non-anatomically correct labeled.

From the standpoint of an ANTs registration, the behavior is not a bug given the input.  If you want further clarification as to the behavior of these ambiguous header scenarios, I recommend you ask over at the ITK discussion forum.

**Comment by cookpa** [comment]
I think there's an additional complication in the pipeline given the different input spaces but can't elaborate until I get on a computer later

**Comment by cookpa** [comment]
I ran the script but there's an error here

> `tx = ants.read_transform(txfile, dimension=2)`

read_transform doesn't take a dimension argument, and in any case we are dealing with three dimensional images.

**Comment by DimitriosGk** [comment]
Hello,
According to the docs, https://buildmedia.readthedocs.org/media/pdf/antspy/latest/antspy.pdf,  p.12, read_transform does take a dimension argument: 'ants.read_transform(filename, dimension=2, precision=’float’)'.

Although, checking the result, adding dimension=2, runs fine on my version of ANTs, but doesn't really result in any difference. 

My main question is, how is this possible that the 'warpedmovout' result produces the 'right' orientation, while applying the same extracted transform to the other volumes is not working in the same way.
At the same time, I did the following 'experiment': Read all images involved as numpy matrices, saved as .nii again using ants.from_numpy() and ants.image_write(). All of them end up with the same sform and still, when I load them again using ants.image_read() and run the script, it seems that the flip is still happening.

Would you have a robust solution or direction to propose for solving this issue?

**Comment by cookpa** [comment]
OK from looking at the input images, I think they are all flipped with respect to the reference. I loaded INV2 into ITK-SNAP

`itksnap -g Magn_echo_1_masked.nii.gz -o GTSPc004_MP2RAGE_INV2_masked.nii.gz`

and used the manual registration tool (Tools -> Registration) to align centers of mass, and manually rotate. 

It looks flipped to me - I think this is obscured by the intial affine, which scales and shears to make the images more similar. Then the deformable SyN can make the overlap look decent.

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/611507/212927628-11d6dcb4-855b-45d2-a260-f49c28ed21ce.png">

The other images look worse because the inverse transforms are being applied. I think

```
fullTrasform = reg[ 'invtransforms'] 
```

should be 

```
fullTrasform = reg[ 'fwdtransforms'] 
```

This won't solve the flip, but makes the output look consistent between the input contrasts

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/611507/212928939-e285557a-2b34-4dea-956b-b8b3f092f2ee.png">

So my recommendation would be:

1. Fix the headers to remove the flip (I'm assuming the reference image is flipped but can't be sure)
2. Do SyN registration with `moving = MP2RAGE_INV2` and `inital_transform = txfile`
3. Apply transforms with `transformlist = reg['fwdtransforms'], whichtoinvert = [False,False]`

If these are intra-subject images, I would also consider what the actual transformation is likely to be. Is the true transform between the images rigid (motion only), rigid + affine, rigid + nonlinear, rigid + affine + nonlinear? That will affect your initialization strategy. The affine_initializer might be unnecessary once the headers are made consistent.

**Comment by cookpa** [comment]
FYI, the readthedocs link above might be from an outdated Google cache. The current one is here

https://antspyx.readthedocs.io/_/downloads/en/stable/pdf/

**Comment by DimitriosGk** [comment]
Hello, 

OK, thanks a lot for the suggestions. I will make sure to keep the updated docs and try to fix the headers issue effectively before moving on to the further registrations optimization.
Dimitri
