### ISSUE TITLE
ANTsImage.new_image_like() creates image with different header information

### ISSUE THREAD

**Issue by pogos-ed** [ANTsX/ANTsPy#428]
When I'm saving ANTs image using **_ants.image_write(image, filename, ri=False)_** or **_ANTsImage.to_file(filename)_**  output file's nifti header is not the same as input one.  

To reproduce the bug, use attached *.nii.gz files and python code below:
```
import ants
pt_folder = 'PATH_TO_YOUR_WORKDIR'  
fs_seg = ants.image_read(pt_folder + 'FS_seg.nii.gz')
fs_seg_arr = fs_seg.numpy()
t1_im = ants.image_read(pt_folder + 't1_n.nii.gz')
tum_seg_im = ants.image_read(pt_folder + 'tumor_segmentation.nii.gz')
tum_seg_im = tum_seg_im.numpy()
seg_mask = t1_im.numpy()
seg_mask[seg_mask > 0] = 1
seg_mask[tum_seg_im > 0] = 0
lbls_to_exclude = [10, 49, 12, 13, 51, 52, 11, 50]
for lbl in lbls_to_exclude:
	seg_mask[fs_seg_arr == lbl] = 0
seg_mask_ants = t1_im.new_image_like(seg_mask)
seg_mask_ants.to_filename(pt_folder + 'seg_area.nii.gz')
```

Then run Atropos in console (python version of Atropos is not working on my PC):
```
Atropos -d 3 -i kmeans[3] -o wm_gm.nii.gz -a t1_n.nii.gz -v -x seg_area.nii.gz
```

As result, you'll see error in console: 

```
Line: 220
Description: itk::ERROR: AtroposSegmentationImageFilter(0x557ef04e6de0): Inputs do not occupy the same physical space! 
InputImage Direction: -9.9832924e-01 2.3681992e-02 -5.2705525e-02
-2.3439654e-02 -9.9971167e-01 -5.2186720e-03
-5.2813922e-02 -3.9673884e-03 9.9859646e-01
, InputImage_1 Direction: -9.9832924e-01 2.3682185e-02 -5.2705611e-02
-2.3439654e-02 -9.9971165e-01 -5.2150850e-03
-5.2813918e-02 -3.9709709e-03 9.9859648e-01

        Tolerance: 1.0000000e-06
```

Installed version of antspyx 0.3.7
[tumor_segmentation.nii.gz](https://github.com/ANTsX/ANTsPy/files/10723353/tumor_segmentation.nii.gz)
[t1_n.nii.gz](https://github.com/ANTsX/ANTsPy/files/10723354/t1_n.nii.gz)
[FS_seg.nii.gz](https://github.com/ANTsX/ANTsPy/files/10723355/FS_seg.nii.gz)

**Comment by ntustison** [comment]
IO is handled by ITK and that's the source of the issue here.  I  recommend using ``ants.copy_image_info()`` or ``CopyImageHeaderInformation`` to ensure that the header information stays the same prior to your Atropos call.

**Comment by cookpa** [comment]
The input images `t1_n.nii.gz` and `tumor_segmentation.nii.gz` have different transforms. This can be seen with ANTs `PrintHeader`.

`tumor_segmentation.nii.gz` has qform_code = NIFTI_XFORM_SCANNER_ANAT and sform_code = NIFTI_XFORM_UNKNOWN.

`t1_n.nii.gz` is the opposite -  qform_code =  NIFTI_XFORM_UNKNOWN and sform_code = NIFTI_XFORM_ALIGNED_ANAT

The NIFTI convention of allowing two different transforms has caused all sorts of problems, one of which is that transforms intended to be identical can be different when encoded with qform vs sform, because of differences in precision. 

Making the input images consistent with `CopyImageHeaderInformation` might solve the problem.


More on this:

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

**Comment by pogos-ed** [comment]
@cookpa , @ntustison , thank you for answers. ```CopyImageHeaderInformation``` doesn't solve the problem. 
Copying header info using nibabel allows to save correct file:
```
import nibabel as nib
img = nib.load(pt_folder + 't1_n.nii.gz')
seg_mask_nib = nib.Nifti1Image(seg_mask, img.affine, img.header)
nib.save(seg_mask_nib, pt_folder + "seg_area.nii.gz")
```

As I understand, the bug is related to ITK, not ANTs. Closing ticket.

**Comment by cookpa** [comment]
Thanks for the update. `CopyImageHeaderInformation` works through ITK so it doesn't always solve the issues. Other software that writes values directly into the header are often useful.
