### ISSUE TITLE
Difference between `ants.apply_transforms` and `transform.apply_to_image` with multiple transforms

### ISSUE THREAD

**Issue by DeanTM** [ANTsX/ANTsPy#684]
Using `ants.apply_transforms` with a list of two transforms yields a different result to loading the individual transforms and applying them separately. However, the result is the same for any *one* transform. This concatenation of transforms seems to yield different behaviour.

```python
import ants
import numpy as np

moving_ants = ants.image_read(ants.get_data("r16"))
fixed_ants = ants.image_read(ants.get_data("r27"))
registration = ants.registration(moving=moving_ants, fixed=fixed_ants, type_of_transform="SyN")

transformed_normal = ants.apply_transforms(
    fixed=fixed_ants,
    moving=moving_ants,
    transformlist=registration['fwdtransforms'],
    )

transformed_manual = moving_ants
transform = ants.transform_from_displacement_field(ants.image_read(registration['fwdtransforms'][0]))
transformed_manual = transform.apply_to_image(transformed_manual, reference=fixed_ants)
transform = ants.read_transform(registration['fwdtransforms'][1])
transformed_manual = transform.apply_to_image(transformed_manual, reference=fixed_ants)

assert np.allclose(transformed_manual[:], transformed_normal[:])  # AssertionError!
```

However, the following works:

```python
## Test just the first transform
transformed_normal = ants.apply_transforms(
    fixed=fixed_ants,
    moving=moving_ants,
    transformlist=registration['fwdtransforms'][:1],
    )
transformed_manual = moving_ants
transform = ants.transform_from_displacement_field(ants.image_read(registration['fwdtransforms'][0]))
transformed_manual = transform.apply_to_image(transformed_manual, reference=fixed_ants)
assert np.allclose(transformed_manual[:], transformed_normal[:])  # Assertion passes!

## Test just the second transform
transformed_normal = ants.apply_transforms(
    fixed=fixed_ants,
    moving=moving_ants,
    transformlist=registration['fwdtransforms'][1:],
    )
transformed_manual = moving_ants
transform = ants.read_transform(registration['fwdtransforms'][1])
transformed_manual = transform.apply_to_image(transformed_manual, reference=fixed_ants)
assert np.allclose(transformed_manual[:], transformed_normal[:])  # Assertion passes!
```

I also tested with the inverse transforms (inverting the affine transform as necessary) and with other data, and found the same results.

I would expect that applying the same transforms in the same order would yield the same results, but it seems that the `ants.apply_transforms` does something to change the result (perhaps an optimisation?). Why is that? Can I turn it off? Is using `ants.apply_transforms` the *correct* way, while using `ANTsTransfrom.apply_to_image` repeatedly is *incorrect*; and if so, is there a way to get the *correct* behaviour from a list of `ANTsTransform` instances?

I'm planning to save the transforms together in HDF5 files (and eventually NWB files) to be shared *with* my data, but this means the `ants.apply_transforms` function isn't immediately accessible; it's easier to build up the transforms from the data in the HDF5 files.

**Comment by cookpa** [comment]
I think there's two issues here. Firstly, if you break the transforms down into two stages, you will interpolate the data twice, so the results will be slightly different because of that.

But more importantly, the transforms are applied in reverse queue order as in the ITK composite transform:

```
This class concatenates transforms in reverse queue order by means of composition: 𝑇0𝑜𝑇1=𝑇0(𝑇1(𝑥)) Transforms are stored in a container (queue), in the following order: 𝑇0,𝑇1,...,𝑇𝑁−1 Transforms are added via a single method, [AddTransform()](https://itk.org/Doxygen/html/classitk_1_1MultiTransform.html#aedf3052f0eb526ce16b2d73cce1d7e8a). This adds the transforms to the back of the queue. A single method for adding transforms is meant to simplify the interface and prevent errors. One use of the class is to optimize only a subset of included transforms.
```

https://itk.org/Doxygen/html/classitk_1_1CompositeTransform.html

So you would do

```
aff_transform = ants.read_transform(registration['fwdtransforms'][1])
transformed_manual_aff = aff_transform.apply_to_image(moving_ants, reference=fixed_ants)
disp_transform = ants.transform_from_displacement_field(ants.image_read(registration['fwdtransforms'][0]))
transformed_manual = diff_transform.apply_to_image(transformed_manual_aff, reference=fixed_ants)
```

Doing this, the images seem to be well aligned in ITK-SNAP, though the interpolation makes them different enough to fail an np.allclose check.

<img width="553" alt="image" src="https://github.com/user-attachments/assets/f28d33af-3bd1-4b04-a933-67379e3a2cb6">

I can get identical results to ants.apply_transforms by using a composite transform

```
transformed_normal_float = ants.apply_transforms(fixed=fixed_ants, moving=moving_ants, transformlist=registration['fwdtransforms'], singleprecision=True)
composite = ants.compose_ants_transforms([disp_transform, aff_transform])
transformed_composite = composite.apply_to_image(moving_ants, reference=fixed_ants)
assert np.allclose(transformed_composite[:], transformed_normal_float[:]) 
```

Note here I used the `singleprecision=True` argument to `apply_transforms` so that the data types of the transform objects match.

**Comment by DeanTM** [comment]
Great answer, thank you @cookpa!

So the transforms are stored in reverse order because they're composed one at a time, something like

```python
reduce(compose, transforms_list)  # one simple, neat line
```

And then `ants.compose_ants_transforms` doesn't just create a new object which applies them in sequence along with interpolation, but instead only interpolates at the end. Makes sense!

**Comment by cookpa** [comment]
I think that's right, but the ordering is crucial and has been a consistent source of trouble even for advanced users, so just to be clear to others, I would not recommend using reduce.

ANTsPy has reasonably decided to preserve the base ANTs command line ordering of transforms. The interfacing with ITK is all handled internally, so you should specify transforms to `ants.compose_ants_transforms` in the same order you would in a call to `ants.applytransforms`.

I have tried to switch my scripts to just use composite transforms throughout, with the `write_composite_transform=True` option to `ants.registration`, because it reduces scope for error and if I really want to separate the transforms, I can do so later.

More details [here](https://discourse.itk.org/t/transformpoint-and-resampling-images/6713) and on the [ANTs Wiki](https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians) for those interested.
