### ISSUE TITLE
Create tiled mosaic arguments not doing anything

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTsPy#81]
**Describe the bug**
The [create_tiled_mosaic](https://github.com/ANTsX/ANTsPy/blob/ad7fcd2e5d832088733ba3dfc0c82cd4043c5876/ants/viz/create_tiled_mosaic.py#L13) function has multiple keyword arguments, but their functionality isn't implemented.

**To Reproduce**
`for direction in range(2): ants.create_tiled_mosaic(data3d, direction=direction)`

**Expected behavior**
Direction changes the projection from sagittal to either coronal or axial.

**Comment by ntustison** [comment]
Can you post a working example with data and a script to reproduce?

**Comment by dangom** [comment]
Of course. Here's a MWE:

```python
import ants
data3d   = ants.image_read(ants.get_data("mni"))
for direction in range(2):
    ants.create_tiled_mosaic(data3d, direction=direction)
```

**Comment by ntustison** [comment]
Okay, I added a couple of options with this [commit](https://github.com/ANTsX/ANTsPy/commit/babe6fcfbc8063ee7d4d82b6bca1cd5e9fee2314) which includes the direction.  However, not all the options are available because I don't quite know what the translation is between the ANTs command line parser (which I wrote with @stnava) and the underlying philosophy behind the ANTsPy approach written by @ncullen93 .  My python skills are at the beginner level with [ANTsPyNet](https://github.com/ANTsX/ANTsPyNet) being my introduction but I'll talk with @stnava as soon as his schedule opens up and try to make the rest of the arguments for ``CreateTiledMosaic`` (which I wrote) available to the ANTsPy user.

**Comment by stnava** [comment]
please re-open if this needs more attention.
