### ISSUE TITLE
ANTsPy is still under development or not?

### ISSUE THREAD

**Issue by liangyuandg** [ANTsX/ANTsPy#94]
I have tried the reigstration functions with ANTsPy. However, I found it can be very different from Ants from two aspects:
1. some functions (for example, affine registration) of them can have different output even with exactly the same parameters.
2. the runtime of ANTsPy is much faster than Ants for most functions (for example, affine registration and Syn registration).

Is the ANTsPy still under development or it is ready to be used as benchmarks for techinique papers?

**Comment by ntustison** [comment]
ANTsPy development is a much more recent project than ANTs.  Although it's still under active development, the principal developer is not as active as they once were due to other commitments.  While @stnava and others still provide support, our knowledge of python is much less than C++ and R.  

ANTsPy is still under development.  But so is ANTs and ANTsR.  We're always fixing bugs and trying to improve the code.  However, ANTsPy can be used as a benchmark as the underlying registration engine derives from ANTs.

**Comment by stnava** [comment]
Indeed - if one carefully sets parameters to be the same, then the results
will be the same.

brian
